anton/profile-page
ets-ninja/frontend pull request #19
Opened 2022-09-27 21:43 UTC by AntonParker18

2022-09-28 10:09 UTC, ValeriaRbk approved these changes

2022-09-28 12:42 UTC, Bogd1y approved these changes

2022-09-29 07:08 UTC, ShevtsovVolodymyr approved these changes

2022-10-02 15:50 UTC, ShevtsovVolodymyr commented on src/components/Layout/Header/Header.jsx
> +                <Avatar alt="Remy Sharp" src={userInfo.userPhoto} />
```suggestion
                <Avatar alt="Remy Sharp" src={userInfo?.userPhoto} />
```

2022-10-02 15:50 UTC, ShevtsovVolodymyr commented on src/components/Layout/Header/Header.jsx
> +                  <Avatar src={userInfo.userPhoto} />
```suggestion
                  <Avatar src={userInfo?.userPhoto} />
```

2022-10-02 15:51 UTC, ShevtsovVolodymyr requested changes
Please consider suggestions to avoid bug with non-signed user

2022-10-03 11:41 UTC, merged